version: '3.8'

services:
  hotelvision-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/hotelvision
      - DATA_DIR=/app/data
      - SUPABASE_URL=https://yourproject.supabase.co
      - SUPABASE_JWT_SECRET=your-jwt-secret
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=hotelvision
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: